title: Parth Patel
logo: 
description:  Cybersecurity Enthusiast and Analyst
I am a detail-oriented Security Analyst with a passion for safeguarding digital environments and mitigating cyber threats. With a strong foundation in log analysis, incident response, and network security, I specialize in using advanced tools like Microsoft Sentinel, Splunk, and the ELK Stack to detect and respond to potential threats effectively.

Having completed my Master’s in Information Systems Security at Concordia University, I have developed and honed my technical skills through hands-on experience with industry-standard tools, vulnerability assessments, and incident investigations. My certifications, including CompTIA Security+ and Certified in Cybersecurity (CC), reflect my dedication to continuous learning and staying ahead in the evolving threat landscape.

theme: jekyll-theme-minimal
